### ISSUE TITLE
如何加载本地资源包

### ISSUE THREAD

**Issue by DavidRicardoWilde** [evgo2017/vue-live2d#1]
需要下载，重新编译吗？

**Comment by evgo2017** [comment]
是的，目前拓展性一般，之后修改了我再给你发邮件。


evgo
evgo2017@qq.com


---原始邮件---
发件人: "JonesWilde"<notifications@github.com&gt;
发送时间: 2020年3月8日(星期日) 凌晨5:38
收件人: "evgo2017/vue-live2d"<vue-live2d@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [evgo2017/vue-live2d] 如何加载本地资源包 (#1)



需要下载，重新编译吗？

**Comment by evgo2017** [comment]
@DavidRicardoWilde 可参考 [live2d-static-api](https://github.com/evgo2017/live2d-static-api)，这样可加载本地资源包。
