### ISSUE TITLE
大佬 在AVue框架下无法使用，能加载就是不出图像能帮忙看一下吗？

### ISSUE THREAD

**Issue by wdd000** [evgo2017/vue-live2d#10]
大佬 在AVue框架下无法使用，能加载就是不出图像能帮忙看一下吗？
https://gitee.com/smallweigit/avue-cli.git

这个框架下不加载，查了几天了 没查出问题 。
按照你的文档一点一点加进去，还是不显示。

**Comment by evgo2017** [comment]
@wdd000 我用这个框架试了下，是依赖的库文件 live2d.min.js 里面的报的两个错误：dump exception : _$SS#loadModel(b) / b _$x be DataView or ArrayBuffer 和 tack :: undefined。因为这个库文件没找到源码，所以这个文件里面出的问题我目前无法解决。之后应该会换掉依赖。见谅。

**Comment by wdd000** [comment]
@evgo2017 好的  不过我这边修改了源码的一部分  可以正常加载live2d这个文件  就是出现不了图像，很奇怪

**Comment by evgo2017** [comment]
@wdd000 哈，解决了，一是 mock，二是 axios 对 http 的配置。

一：Network 内发现一直在发送请求，把框架内的 mock （/src/mock/index.js 全注释掉）关掉，可以正常显示了。

二：点击切换语言和模型，HTTP 请求失败，再把 axios（src/router/axios.js） 内对 HTTP 请求的配置axios.defaults.withCredentials，以及 axios.interceptors.request 和 axios.interceptors.response 内的 config 除 return 语句外注释掉（为了简洁），OK了。

需要你具体调一下框架相关逻辑。

**Comment by wdd000** [comment]
@evgo2017 好的 谢谢  我按照你的写法改一下 试试看

**Comment by wdd000** [comment]
感谢🙏 已经解决了！
