### ISSUE TITLE
VUE3支持吗？

### ISSUE THREAD

**Issue by Jadramcool** [evgo2017/vue-live2d#16]
请问VUE3，我引入了，但是只有模型，没有那些按钮啥的，是需要自己配置吗？

**Comment by evgo2017** [comment]
@Jadramcool 你好，我测试了下，是支持的，没有什么问题。

对于“按钮”，我有两种理解：
① 如果是没有展示页面的居左居右等一排排操作按钮，这个是需要自己配置的。可参考源码的 `example/App.vue` 文件。
② 如果是没有跟随模型的按钮，是bug。

**Comment by Jadramcool** [comment]
我的意思应该是第二种，跟随模型的那一列按钮，鼠标放上去模型会自动往左偏移，应该就是给右侧的按钮挪位置，但是按钮不出现。

**Comment by evgo2017** [comment]
@Jadramcool 问题已解决，在部署新版本的时候复现了这个问题，应该是因为 fa-* 类名和 svg css 原因，更新最新版本至 1.3.1 即可（注意 1.3.0 更新了内置的 api 服务）。
