### ISSUE TITLE
jsdeliver被墙了，模型无法加载

### ISSUE THREAD

**Issue by Leng-Kmust** [evgo2017/vue-live2d#17]
如题，有什么解决办法吗

**Comment by evgo2017** [comment]
@Leng-Kmust 修改为能提供服务的 apiPath 即可，如自建服务器。现在在修改提供模型地址的新方案，提交后会 @ 你。

**Comment by evgo2017** [comment]
@Leng-Kmust 问题已解决，更新 vue-live2d 到最新版本 v1.3.1 即可。新写了一个 https://github.com/evgo2017/live2d-static-api 项目来代替之前的 api 服务，若想自定义模型等，可参考此项目。
