### ISSUE TITLE
不要尝试npm install vue-live2d

### ISSUE THREAD

**Issue by TAN00XU** [evgo2017/vue-live2d#18]
不要尝试使用npm install vue-live2d，这会损坏你的项目，导致项目无法构建

**Comment by FodderFish** [comment]
'pushScopeId' is not exported by node_modules/vue-live2d/node_modules/vue/dist/vue.runtime.esm.js, imported by node_modules/vue-live2d/src/index.vue
error during build:
Error: 'pushScopeId' is not exported by node_modules/vue-live2d/node_modules/vue/dist/vue.runtime.esm.js, imported by node_modules/vue-live2d/src/index.vue

**Comment by evgo2017** [comment]
@FodderFish 抱歉，之前在忙其他事情。之后会统一处理。

**Comment by evgo2017** [comment]
@FodderFish 怀疑与 #22 是相同的问题，请尝试新版本 `npm install vue-live2d@1.3.3`。
