### ISSUE TITLE
vue-live2d不支持vue3

### ISSUE THREAD

**Issue by logan-feiyv** [evgo2017/vue-live2d#21]

**Comment by evgo2017** [comment]
@logan-feiyv 抱歉，之前在忙其他事情。之后会统一处理。

**Comment by evgo2017** [comment]
@logan-feiyv 是 vite build 的问题，改为 vue-cli-service build 即可。

**Comment by evgo2017** [comment]
@logan-feiyv 已修复发布新版，`npm install vue-live2d@1.3.3`。非常感谢  #22（@YiguiDing）   提供的信息和解决方案。
