### ISSUE TITLE
可以cdn引入嘛大佬

### ISSUE THREAD

**Issue by 517487575** [evgo2017/vue-live2d#3]

**Comment by evgo2017** [comment]
@517487575 应该可以的，记得还有 css。

**Comment by 517487575** [comment]
> @517487575 应该可以的，记得还有 css。
cdn引入时暴露的变量名是什么呀

**Comment by evgo2017** [comment]
@517487575 `live2d`。可以参考下 `src` 文件夹的示例。

**Comment by evgo2017** [comment]
@517487575 我测试了下，并不方便，需要自己配置 webpack 的 externals 等内容。建议在项目内直接引入此组件。
