### ISSUE TITLE
获取live-2d人物模型的api好像挂了

### ISSUE THREAD

**Issue by 517487575** [evgo2017/vue-live2d#4]
获取live-2d人物模型的api好像挂了

**Comment by 517487575** [comment]
刚看到可以自己改,- -

**Comment by evgo2017** [comment]
@517487575 默认的 API 是其他人的，你可以找一个新的提供地址或者自己搭建一个（这一块我还没涉及到，之后会再完善）。

**Comment by 517487575** [comment]
> @517487575 默认的 API 是其他人的，你可以找一个新的提供地址或者自己搭建一个（这一块我还没涉及到，之后会再完善）。

我正在查api呢,本来说要不要试下搭一个,原来的api地址又可以用了oWo

**Comment by evgo2017** [comment]
ok，上次看到解决了就忘回复了，我关闭这个 issue 了。
