### ISSUE TITLE
大佬你的博客上没看到看板娘啊

### ISSUE THREAD

**Issue by Yakumo-Yukari** [evgo2017/vue-live2d#5]

**Comment by evgo2017** [comment]
@Yakumo-Yukari 上次更新的时候去掉了，最近有点忙，之后再提供新地址。效果跟动图差不多的，也可以代码在本地跑下看看（也是使用示例）。不好意思哈。

**Comment by Yakumo-Yukari** [comment]
> @Yakumo-Yukari 上次更新的时候去掉了，最近有点忙，之后再提供新地址。效果跟动图差不多的，也可以代码在本地跑下看看（也是使用示例）。不好意思哈。

好的！！！
